# CMake generated Testfile for 
# Source directory: /home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test
# Build directory: /home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(args-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/args-test")
set_tests_properties(args-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;62;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(assert-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/assert-test")
set_tests_properties(assert-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;63;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(chrono-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/chrono-test")
set_tests_properties(chrono-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;64;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(color-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/color-test")
set_tests_properties(color-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;65;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(core-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/core-test")
set_tests_properties(core-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;66;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(gtest-extra-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/gtest-extra-test")
set_tests_properties(gtest-extra-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;67;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(format-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/format-test")
set_tests_properties(format-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;68;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(format-impl-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/format-impl-test")
set_tests_properties(format-impl-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;73;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(ostream-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/ostream-test")
set_tests_properties(ostream-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;75;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(compile-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/compile-test")
set_tests_properties(compile-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;76;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(compile-fp-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/compile-fp-test")
set_tests_properties(compile-fp-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;77;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(printf-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/printf-test")
set_tests_properties(printf-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;82;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(ranges-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/ranges-test")
set_tests_properties(ranges-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;83;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(scan-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/scan-test")
set_tests_properties(scan-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;85;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(std-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/std-test")
set_tests_properties(std-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;91;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(unicode-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/unicode-test")
set_tests_properties(unicode-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;100;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(xchar-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/xchar-test")
set_tests_properties(xchar-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;104;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(enforce-checks-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/enforce-checks-test")
set_tests_properties(enforce-checks-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;105;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(posix-mock-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/posix-mock-test")
set_tests_properties(posix-mock-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;149;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
add_test(os-test "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/bin/os-test")
set_tests_properties(os-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;55;add_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;150;add_fmt_test;/home/ivo/projects/private/Engine/engine/lib/fmt-10.2.0/test/CMakeLists.txt;0;")
subdirs("gtest")
